### ISSUE TITLE
Pickle regeneration fails in rrinit

### ISSUE THREAD

**Issue by mnm678** [pkmoore/rrapper#32]
rrinit fails with the following error:

syscall_definitions.pickle does NOT exist. Regenerating.
Traceback (most recent call last):
  File "/home/marinamoore/rrapper/crashsim/bin/rrinit", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'rrinit')()
  File "build/bdist.linux-i686/egg/src/rrinit.py", line 115, in main
  File "build/bdist.linux-i686/egg/src/parse_syscall_definitions.py", line 225, in generate_pickle
  File "build/bdist.linux-i686/egg/src/parse_syscall_definitions.py", line 115, in get_syscall_definitions_list
  File "/home/marinamoore/rrapper/crashsim/local/lib/python2.7/site-packages/sysDef/SyscallManual.py", line 138, in __init__
    self.type, self.definition = self._parse_definition(self.name)
  File "/home/marinamoore/rrapper/crashsim/local/lib/python2.7/site-packages/sysDef/SyscallManual.py", line 403, in _parse_definition
    assert len(similar_definitions) <= 1
AssertionError

**Comment by ex0dus-0x** [comment]
Was this generated through the Docker script? Or was this done using the manual installation process?

**Comment by mnm678** [comment]
It was done through manual installation.

**Comment by ex0dus-0x** [comment]
This is probably due to the fact that many extraneous system calls that aren't part of the standard library were present and threw up an assertion exception. Nevertheless, this should be fixed in https://github.com/pkmoore/posix-omni-parser/pull/8.
