### ISSUE TITLE
rreplay fails when the "trace_snip.strace" file contains "exit_group(0"

### ISSUE THREAD

**Issue by AnoopNadig** [pkmoore/rrapper#37]
When trying to run rreplay when the "trace_snip.strace" file contains "exit_group(0" the following errors occur:
```
Traceback (most recent call last):
  File "/home/alex/rrapper/crashsim/bin/inject", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'inject')()
  File "build/bdist.linux-i686/egg/src/inject.py", line 518, in main
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/posix_omni_parser/Trace.py", line 109, in __init__
    self.syscalls = self.parser.parse_trace()
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/posix_omni_parser/parsers/StraceParser.py", line 579, in parse_trace
    line_parts = self._parse_line(line, unfinished_syscalls)
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/posix_omni_parser/parsers/StraceParser.py", line 752, in _parse_line
    + line + "`")
Exception: Invalid format when parsing completed trace line `3963  exit_group(0`
Injector for event:rec_pid 164:3963 failed
```
The fix for this was to not include the line containing "exit_group(0"  when configuring rrtest or by manually removing the "exit_group(0" line from the  "trace_snip.strace" file

**Comment by pkmoore** [comment]
@alyptik Did we ever figure out what was causing this half-line to be emitted?

**Comment by alyptik** [comment]
@pkmoore My theory is the `_No_return` attribute of `exit_group` but I haven't been able to confirm it yet.

**Comment by pkmoore** [comment]
Workaround implemented
