### ISSUE TITLE
rreplay fails when number of lines are less than the default value in "trace_snip.strace" file

### ISSUE THREAD

**Issue by AnoopNadig** [pkmoore/rrapper#38]
When trying to run rreplay when the "trace_snip.strace" file contains than 5 lines (default length) the following errors occur:
```
Traceback (most recent call last):
  File "/home/alex/rrapper/crashsim/bin/inject", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'inject')()
  File "build/bdist.linux-i686/egg/src/inject.py", line 557, in main
IndexError: list index out of range
Injector for event:rec_pid 164:3963 failed
```
The fix for this was by using the "--sniplen" option when configuring the rrtest.

**Comment by ex0dus-0x** [comment]
Thanks for the report!

Are you selecting a system call towards the end of trace execution?

**Comment by AnoopNadig** [comment]
Yes, this was a system call towards the end of trace execution where only 3 lines were loaded into my 'trace_snip.strace' file.

**Comment by pkmoore** [comment]
@ex0dus-0x Any update on this issue?
