### ISSUE TITLE
Add support for 307(faccessat)

### ISSUE THREAD

**Issue by akbisw** [pkmoore/rrapper#42]
For tool called "which". Attached the relevant traceback below:
```
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 571, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 382, in handle_syscall
    syscall_object.name))
NotImplementedError: Encountered un-ignored syscall entry with no handler: 307(faccessat)
Failed to complete trace
Injector for event:rec_pid 218:5413 failed
```

**Comment by pkmoore** [comment]
Can you pull:

https://github.com/pkmoore/rrapper/pull/44

and let me know it works?

**Comment by pkmoore** [comment]
Merged
