### ISSUE TITLE
rreplay fails: Invalid Syntax

### ISSUE THREAD

**Issue by aab641** [pkmoore/rrapper#45]
When performing the rreplay while testing the "echo hello" command.
Using the latest master version.

Traceback (most recent call last):
  File "/home/alex/rrapper/crashsim/bin/inject", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'inject')()
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/rrapper-0.1.0-py2.7-linux-i686.egg/src/inject.py", line 317
    (250), True): generic_handlers.syscall_return_success_handler,
         ^
SyntaxError: invalid syntax
Injector for event:rec_pid 179:1571 failed

**Comment by pkmoore** [comment]
This should be fixed now!  Dumb typo on my part.  Sorry about that!  Re-pull and let me know if it is still broken.
