### ISSUE TITLE
Munmap not implemented

### ISSUE THREAD

**Issue by aab641** [pkmoore/rrapper#47]
Hi,
rrapper raises an error when trying to analyze the 'echo' command.
To re-create the error. Follow these steps...

```
rrtest create --name echotest --command "../../../../../../../bin/echo echo_this_text"
```

```
rrtest configure --name echotest --traceline 74
Enter event number: 179
```

```
rreplay echotest

DEBUG:root:Injecting 1915
DEBUG:root:Attached 1915
DEBUG:root:Requesting stop at next system call entry using SIGCONT
DEBUG:root:Second sigcont 1915
DEBUG:root:Entering system call handling loop
DEBUG:root:Handling syscall
DEBUG:root:Entering fstat64 handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 1
DEBUG:root:Argument from trace: 1
DEBUG:root:ECX: bfffee6c
DEBUG:root:Nooping the current system call in pid: 1915
DEBUG:root:Got successful stat-like call
DEBUG:root:st_dev1: 0
DEBUG:root:st_dev2: 21
DEBUG:root:We have a st_rdev argument
DEBUG:root:st_rdev1: 136
DEBUG:root:st_rdev2: 0
DEBUG:root:st_ino: 3
DEBUG:root:Cleaning up st_mode
DEBUG:root:Found st_mode parts: ['S_IFCHR', '0620']
DEBUG:root:Got part: S_IFCHR
DEBUG:root:Interpreting part as S_<CONST>
DEBUG:root:Part value in base 10: 8192
DEBUG:root:Part value in base 8: 020000
DEBUG:root:New value for tmp: 8192
DEBUG:root:Got part: 0620
DEBUG:root:Interpreting part as base 8 int
DEBUG:root:Part value in base 10: 400
DEBUG:root:Part value in base 8: 0620
DEBUG:root:New value for tmp: 8592
DEBUG:root:Final value for tmp: 8592
DEBUG:root:st_mode: 8592
DEBUG:root:st_nlink: 1
DEBUG:root:st_uid: 1000
DEBUG:root:st_gid: 5
DEBUG:root:st_blksize: 1024
DEBUG:root:st_block: 0
DEBUG:root:optional st_size not present
DEBUG:root:st_atime: 1542329928
DEBUG:root:st_mtime: 1542329928
DEBUG:root:st_ctime: 1542316277
DEBUG:root:pid: 1915
DEBUG:root:addr: bfffee6c
C: populate_stat64: child 1915
C: populate_stat64: addr 0xbfffee6c
C: populate_stat64: s 0xbfffe6c0
C: populate_stat64: sizeof(s) 88
C: populate_stat64: st_mode 8592
REG: 0
REG2: 1
sizeof(st.dev): 8
s.st_dev: 21
sizeof(s.st_rdev): 8
s.st_rdev: 34816
sizeof(s.st_ino): 4
s.st_ino: 3
sizeof(s.st_mode): 4
s.st_mode: 8592
sizeof(s.st_nlink): 4
s.st_nlink: 1
sizeof(s.st_uid): 4
s.st_uid: 1000
sizeof(s.st_gid): 4
s.st_gid: 5
sizeof(s.st_size): 8
s.st_size: 0
sizeof(s.st_blksize): 4
s.st_blksize: 1024
sizeof(s.st_blocks): 8
s.st_blocks: 0
s.st_ctime: 2018/11/-0800u 13:v
s.st_mtime: 2018/11/-0800u 16:v
s.st_atime: 2018/11/-0800u 16:v
C: copy_buffer: number of writes: 85
C: copy_buffer: buffer data: 
15 00 00 00 00 00 00 00 00 00 00 00 03 00 00 00 90 21 00 00 01 00 00 00 E8 03 00 00 05 00 00 00 00 88 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 48 16 EE 5B 00 00 00 00 48 16 EE 5B 00 00 00 00 F5 E0 ED 5B 00 00 00 00 C: copy_buffer: buffer data(ASCII): 
                � !       �         �                               H  � [     H  � [     � � � [     
C: copy_buffer: poking (0xbfffe6c0)00000015 into 0xbfffee6c
C: copy_buffer: poking (0xbfffe6c1)00000000 into 0xbfffee6d
C: copy_buffer: poking (0xbfffe6c2)00000000 into 0xbfffee6e
C: copy_buffer: poking (0xbfffe6c3)00000000 into 0xbfffee6f
C: copy_buffer: poking (0xbfffe6c4)00000000 into 0xbfffee70
C: copy_buffer: poking (0xbfffe6c5)00000000 into 0xbfffee71
C: copy_buffer: poking (0xbfffe6c6)00000000 into 0xbfffee72
C: copy_buffer: poking (0xbfffe6c7)00000000 into 0xbfffee73
C: copy_buffer: poking (0xbfffe6c8)00000000 into 0xbfffee74
C: copy_buffer: poking (0xbfffe6c9)03000000 into 0xbfffee75
C: copy_buffer: poking (0xbfffe6ca)00030000 into 0xbfffee76
C: copy_buffer: poking (0xbfffe6cb)00000300 into 0xbfffee77
C: copy_buffer: poking (0xbfffe6cc)00000003 into 0xbfffee78
C: copy_buffer: poking (0xbfffe6cd)90000000 into 0xbfffee79
C: copy_buffer: poking (0xbfffe6ce)21900000 into 0xbfffee7a
C: copy_buffer: poking (0xbfffe6cf)00219000 into 0xbfffee7b
C: copy_buffer: poking (0xbfffe6d0)00002190 into 0xbfffee7c
C: copy_buffer: poking (0xbfffe6d1)01000021 into 0xbfffee7d
C: copy_buffer: poking (0xbfffe6d2)00010000 into 0xbfffee7e
C: copy_buffer: poking (0xbfffe6d3)00000100 into 0xbfffee7f
C: copy_buffer: poking (0xbfffe6d4)00000001 into 0xbfffee80
C: copy_buffer: poking (0xbfffe6d5)E8000000 into 0xbfffee81
C: copy_buffer: poking (0xbfffe6d6)03E80000 into 0xbfffee82
C: copy_buffer: poking (0xbfffe6d7)0003E800 into 0xbfffee83
C: copy_buffer: poking (0xbfffe6d8)000003E8 into 0xbfffee84
C: copy_buffer: poking (0xbfffe6d9)05000003 into 0xbfffee85
C: copy_buffer: poking (0xbfffe6da)00050000 into 0xbfffee86
C: copy_buffer: poking (0xbfffe6db)00000500 into 0xbfffee87
C: copy_buffer: poking (0xbfffe6dc)00000005 into 0xbfffee88
C: copy_buffer: poking (0xbfffe6dd)00000000 into 0xbfffee89
C: copy_buffer: poking (0xbfffe6de)88000000 into 0xbfffee8a
C: copy_buffer: poking (0xbfffe6df)00880000 into 0xbfffee8b
C: copy_buffer: poking (0xbfffe6e0)00008800 into 0xbfffee8c
C: copy_buffer: poking (0xbfffe6e1)00000088 into 0xbfffee8d
C: copy_buffer: poking (0xbfffe6e2)00000000 into 0xbfffee8e
C: copy_buffer: poking (0xbfffe6e3)00000000 into 0xbfffee8f
C: copy_buffer: poking (0xbfffe6e4)00000000 into 0xbfffee90
C: copy_buffer: poking (0xbfffe6e5)00000000 into 0xbfffee91
C: copy_buffer: poking (0xbfffe6e6)00000000 into 0xbfffee92
C: copy_buffer: poking (0xbfffe6e7)00000000 into 0xbfffee93
C: copy_buffer: poking (0xbfffe6e8)00000000 into 0xbfffee94
C: copy_buffer: poking (0xbfffe6e9)00000000 into 0xbfffee95
C: copy_buffer: poking (0xbfffe6ea)00000000 into 0xbfffee96
C: copy_buffer: poking (0xbfffe6eb)00000000 into 0xbfffee97
C: copy_buffer: poking (0xbfffe6ec)00000000 into 0xbfffee98
C: copy_buffer: poking (0xbfffe6ed)00000000 into 0xbfffee99
C: copy_buffer: poking (0xbfffe6ee)00000000 into 0xbfffee9a
C: copy_buffer: poking (0xbfffe6ef)00000000 into 0xbfffee9b
C: copy_buffer: poking (0xbfffe6f0)00000000 into 0xbfffee9c
C: copy_buffer: poking (0xbfffe6f1)00000000 into 0xbfffee9d
C: copy_buffer: poking (0xbfffe6f2)04000000 into 0xbfffee9e
C: copy_buffer: poking (0xbfffe6f3)00040000 into 0xbfffee9f
C: copy_buffer: poking (0xbfffe6f4)00000400 into 0xbfffeea0
C: copy_buffer: poking (0xbfffe6f5)00000004 into 0xbfffeea1
C: copy_buffer: poking (0xbfffe6f6)00000000 into 0xbfffeea2
C: copy_buffer: poking (0xbfffe6f7)00000000 into 0xbfffeea3
C: copy_buffer: poking (0xbfffe6f8)00000000 into 0xbfffeea4
C: copy_buffer: poking (0xbfffe6f9)00000000 into 0xbfffeea5
C: copy_buffer: poking (0xbfffe6fa)00000000 into 0xbfffeea6
C: copy_buffer: poking (0xbfffe6fb)00000000 into 0xbfffeea7
C: copy_buffer: poking (0xbfffe6fc)00000000 into 0xbfffeea8
C: copy_buffer: poking (0xbfffe6fd)48000000 into 0xbfffeea9
C: copy_buffer: poking (0xbfffe6fe)16480000 into 0xbfffeeaa
C: copy_buffer: poking (0xbfffe6ff)EE164800 into 0xbfffeeab
C: copy_buffer: poking (0xbfffe700)5BEE1648 into 0xbfffeeac
C: copy_buffer: poking (0xbfffe701)005BEE16 into 0xbfffeead
C: copy_buffer: poking (0xbfffe702)00005BEE into 0xbfffeeae
C: copy_buffer: poking (0xbfffe703)0000005B into 0xbfffeeaf
C: copy_buffer: poking (0xbfffe704)00000000 into 0xbfffeeb0
C: copy_buffer: poking (0xbfffe705)48000000 into 0xbfffeeb1
C: copy_buffer: poking (0xbfffe706)16480000 into 0xbfffeeb2
C: copy_buffer: poking (0xbfffe707)EE164800 into 0xbfffeeb3
C: copy_buffer: poking (0xbfffe708)5BEE1648 into 0xbfffeeb4
C: copy_buffer: poking (0xbfffe709)005BEE16 into 0xbfffeeb5
C: copy_buffer: poking (0xbfffe70a)00005BEE into 0xbfffeeb6
C: copy_buffer: poking (0xbfffe70b)0000005B into 0xbfffeeb7
C: copy_buffer: poking (0xbfffe70c)00000000 into 0xbfffeeb8
C: copy_buffer: poking (0xbfffe70d)F5000000 into 0xbfffeeb9
C: copy_buffer: poking (0xbfffe70e)E0F50000 into 0xbfffeeba
C: copy_buffer: poking (0xbfffe70f)EDE0F500 into 0xbfffeebb
C: copy_buffer: poking (0xbfffe710)5BEDE0F5 into 0xbfffeebc
C: copy_buffer: poking (0xbfffe711)005BEDE0 into 0xbfffeebd
C: copy_buffer: poking (0xbfffe712)00005BED into 0xbfffeebe
C: copy_buffer: poking (0xbfffe713)0000005B into 0xbfffeebf
C: copy_buffer: poking (0xbfffe714)00000000 into 0xbfffeec0
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:write entry handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 1
DEBUG:root:Argument from trace: 1
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 15
DEBUG:root:Argument from trace: 15
####   Output   ####
echo_this_text
#### End Output ####
DEBUG:root:Nooping the current system call in pid: 1915
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 15
DEBUG:root:Injecting return value 15
DEBUG:root:Handling syscall
DEBUG:root:Entering close entry handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 1
DEBUG:root:Argument from trace: 1
DEBUG:root:Nooping the current system call in pid: 1915
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:brk entry handler
DEBUG:root:Validating address argument (trace position: 0 execution position: 0)
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 386, in handle_syscall
    handlers[(syscall_id, entering)](syscall_id, syscall_object, pid)
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/syscallreplay/kernel_handlers.py", line 65, in brk_entry_handler
    raise NotImplementedError('munmap required here! Not implemented!')
NotImplementedError: munmap required here! Not implemented!
Failed to complete trace
Injector for event:rec_pid 179:1908 failed

```

**Comment by pkmoore** [comment]
So this is actually a flavor of the brk() system call that moves the program break backwards (thereby deallocating memory) instead of moving it forward.  This is will be more complicated to implement than some simpler calls.  You may have to adjust your configuration to avoid that brk() call.  Maybe two tests -- one for calls before and one for calls after.
