### ISSUE TITLE
mutator incorrectly handling stat64 syscall

### ISSUE THREAD

**Issue by akbisw** [pkmoore/rrapper#48]
mutator CONFIG:
```
(crashsim) alex@ubuntu:~/rrapper/test_which$ cat ~/.crashsim/which/config.ini
[rr_recording]
rr_dir = /home/alex/.crashsim/which/

[request_handling_process]
event = 218
pid = 8435
trace_file = /home/alex/.crashsim/which/trace_snip.strace
trace_start = 0
trace_end = 5
mutator = UnusualFiletypeMutator("S_IFDIR")
```

TRACE_SNIP:
```
"~/.crashsim/which/trace_snip.strace" 5L, 569C                                                1,1           All
8435  stat64("/bin/ls", {st_dev=makedev(8, 1), st_ino=262228, st_mode=S_IFDIR|0755, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=288, st_size=145144, st_atime=1542293672 /* 2018-11-15T06:54:32.231983444-0800 */, st_atime_nsec=231983444, st_mtime=1516268629 /* 2018-01-18T01:43:49-0800 */, st_mtime_nsec=0, st_ctime=1541552655 /* 2018-11-06T17:04:15.493711012-0800 */, st_ctime_nsec=493711012}) = 0
8435  geteuid()                         = 1000
8435  faccessat(AT_FDCWD, "/bin/ls", X_OK) = 0
8435  write(1, "/bin/ls\n", 8)          = 8
8435  exit_group(0
```

RREPLAY Traceback:
```
(crashsim) alex@ubuntu:~/rrapper/test_which$ rreplay which
Traceback (most recent call last):
  File "/home/alex/rrapper/crashsim/bin/inject", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'inject')()
  File "build/bdist.linux-i686/egg/src/inject.py", line 540, in main
  File "build/bdist.linux-i686/egg/src/mutator/UnusualFiletype.py", line 29, in mutate_trace
TypeError: list indices must be integers, not NoneType
Injector for event:rec_pid 218:8435 failed
```

File mentioned in error:
https://github.com/pkmoore/rrapper/blob/8da75a09794f5d07f2be06d56e91a892ea7ff3cd/src/mutator/UnusualFiletype.py#L29

**Comment by pkmoore** [comment]
Thanks for the detailed info.  I am able to reproduce this bug.  Stay tuned
