### ISSUE TITLE
getuid32 not implemented

### ISSUE THREAD

**Issue by mnm678** [pkmoore/rrapper#52]
When setting up a test for perl rreplay failed with the following error:
```
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 385, in handle_syscall
    syscall_object.name))
NotImplementedError: Encountered un-ignored syscall entry with no handler: 199(getuid32)
Failed to complete trace
Injector for event:rec_pid 268:13011 failed
```

The perl file I was testing was:
```
$variable = 5;
print "$variable\n";
```

**Comment by pkmoore** [comment]
I have a tentative fix here: https://github.com/pkmoore/rrapper/pull/53

Can you pull that PR, install it, and let me know if it fixes things?  It should be fine so if I don't hear back I'll merge it later on tonight either way.

Thanks,
PReston

**Comment by pkmoore** [comment]
merged
