### ISSUE TITLE
access not implemented

### ISSUE THREAD

**Issue by snahil28** [pkmoore/rrapper#56]
While running rreplay on uptime after executing the  reconfigure command
``` rrtest configure --name uptime_test2 --traceline 283 --sniplen=20 ``` , got below error -

```
DEBUG:root:Injecting 7167
DEBUG:root:Attached 7167
DEBUG:root:Requesting stop at next system call entry using SIGCONT
DEBUG:root:Second sigcont 7167
DEBUG:root:Entering system call handling loop
DEBUG:root:Handling syscall
DEBUG:root:Entering time entry handler
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Got successful time call
DEBUG:root:time: 1542671204
DEBUG:root:addr: -1073745996
DEBUG:root:Populating the time_t
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 1542671204
DEBUG:root:Injecting return value 1542671204
DEBUG:root:Handling syscall
DEBUG:root:Entering openat entry handler
DEBUG:root:Filename from trace: /etc/localtime
DEBUG:root:Filename from execution: /etc/localtime
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 3
DEBUG:root:Injecting return value 3
DEBUG:root:Handling syscall
DEBUG:root:Entering fstat64 handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:ECX: bfffee48
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Got successful stat-like call
DEBUG:root:st_dev1: 8
DEBUG:root:st_dev2: 1
DEBUG:root:st_ino: 2230664
DEBUG:root:Cleaning up st_mode
DEBUG:root:Found st_mode parts: ['S_IFREG', '0644']
DEBUG:root:Got part: S_IFREG
DEBUG:root:Interpreting part as S_<CONST>
DEBUG:root:Part value in base 10: 32768
DEBUG:root:Part value in base 8: 0100000
DEBUG:root:New value for tmp: 32768
DEBUG:root:Got part: 0644
DEBUG:root:Interpreting part as base 8 int
DEBUG:root:Part value in base 10: 420
DEBUG:root:Part value in base 8: 0644
DEBUG:root:New value for tmp: 33188
DEBUG:root:Final value for tmp: 33188
DEBUG:root:st_mode: 33188
DEBUG:root:st_nlink: 1
DEBUG:root:st_uid: 0
DEBUG:root:st_gid: 0
DEBUG:root:st_blksize: 4096
DEBUG:root:st_block: 8
DEBUG:root:st_size: 2845
DEBUG:root:st_atime: 1542644838
DEBUG:root:st_mtime: 1542644838
DEBUG:root:st_ctime: 1542057997
DEBUG:root:pid: 7167
DEBUG:root:addr: bfffee48
C: populate_stat64: child 7167
C: populate_stat64: addr 0xbfffee48
C: populate_stat64: s 0xbfffe6d0
C: populate_stat64: sizeof(s) 88
C: populate_stat64: st_mode 33188
REG: 1
REG2: 1
sizeof(st.dev): 8
s.st_dev: 2049
sizeof(s.st_rdev): 8
s.st_rdev: 0
sizeof(s.st_ino): 4
s.st_ino: 2230664
sizeof(s.st_mode): 4
s.st_mode: 33188
sizeof(s.st_nlink): 4
s.st_nlink: 1
sizeof(s.st_uid): 4
s.st_uid: 0
sizeof(s.st_gid): 4
s.st_gid: 0
sizeof(s.st_size): 8
s.st_size: 2845
sizeof(s.st_blksize): 4
s.st_blksize: 4096
sizeof(s.st_blocks): 8
s.st_blocks: 8
s.st_ctime: 2018/11/-0800u 13:v
s.st_mtime: 2018/11/-0800u 08:v
s.st_atime: 2018/11/-0800u 08:v
C: copy_buffer: number of writes: 85
C: copy_buffer: buffer data: 
01 08 00 00 00 00 00 00 00 00 00 00 88 09 22 00 A4 81 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1D 0B 00 00 00 00 00 00 00 10 00 00 08 00 00 00 00 00 00 00 66 E4 F2 5B 00 00 00 00 66 E4 F2 5B 00 00 00 00 0D F0 E9 5B 00 00 00 00 C: copy_buffer: buffer data(ASCII): 
           � 	 "  � �                            
 � � [                                                                 f � � [     f � � [     
C: copy_buffer: poking (0xbfffe6d0)00000801 into 0xbfffee48
C: copy_buffer: poking (0xbfffe6d1)00000008 into 0xbfffee49
C: copy_buffer: poking (0xbfffe6d2)00000000 into 0xbfffee4a
C: copy_buffer: poking (0xbfffe6d3)00000000 into 0xbfffee4b
C: copy_buffer: poking (0xbfffe6d4)00000000 into 0xbfffee4c
C: copy_buffer: poking (0xbfffe6d5)00000000 into 0xbfffee4d
C: copy_buffer: poking (0xbfffe6d6)00000000 into 0xbfffee4e
C: copy_buffer: poking (0xbfffe6d7)00000000 into 0xbfffee4f
C: copy_buffer: poking (0xbfffe6d8)00000000 into 0xbfffee50
C: copy_buffer: poking (0xbfffe6d9)88000000 into 0xbfffee51
C: copy_buffer: poking (0xbfffe6da)09880000 into 0xbfffee52
C: copy_buffer: poking (0xbfffe6db)22098800 into 0xbfffee53
C: copy_buffer: poking (0xbfffe6dc)00220988 into 0xbfffee54
C: copy_buffer: poking (0xbfffe6dd)A4002209 into 0xbfffee55
C: copy_buffer: poking (0xbfffe6de)81A40022 into 0xbfffee56
C: copy_buffer: poking (0xbfffe6df)0081A400 into 0xbfffee57
C: copy_buffer: poking (0xbfffe6e0)000081A4 into 0xbfffee58
C: copy_buffer: poking (0xbfffe6e1)01000081 into 0xbfffee59
C: copy_buffer: poking (0xbfffe6e2)00010000 into 0xbfffee5a
C: copy_buffer: poking (0xbfffe6e3)00000100 into 0xbfffee5b
C: copy_buffer: poking (0xbfffe6e4)00000001 into 0xbfffee5c
C: copy_buffer: poking (0xbfffe6e5)00000000 into 0xbfffee5d
C: copy_buffer: poking (0xbfffe6e6)00000000 into 0xbfffee5e
C: copy_buffer: poking (0xbfffe6e7)00000000 into 0xbfffee5f
C: copy_buffer: poking (0xbfffe6e8)00000000 into 0xbfffee60
C: copy_buffer: poking (0xbfffe6e9)00000000 into 0xbfffee61
C: copy_buffer: poking (0xbfffe6ea)00000000 into 0xbfffee62
C: copy_buffer: poking (0xbfffe6eb)00000000 into 0xbfffee63
C: copy_buffer: poking (0xbfffe6ec)00000000 into 0xbfffee64
C: copy_buffer: poking (0xbfffe6ed)00000000 into 0xbfffee65
C: copy_buffer: poking (0xbfffe6ee)00000000 into 0xbfffee66
C: copy_buffer: poking (0xbfffe6ef)00000000 into 0xbfffee67
C: copy_buffer: poking (0xbfffe6f0)00000000 into 0xbfffee68
C: copy_buffer: poking (0xbfffe6f1)00000000 into 0xbfffee69
C: copy_buffer: poking (0xbfffe6f2)00000000 into 0xbfffee6a
C: copy_buffer: poking (0xbfffe6f3)00000000 into 0xbfffee6b
C: copy_buffer: poking (0xbfffe6f4)00000000 into 0xbfffee6c
C: copy_buffer: poking (0xbfffe6f5)00000000 into 0xbfffee6d
C: copy_buffer: poking (0xbfffe6f6)00000000 into 0xbfffee6e
C: copy_buffer: poking (0xbfffe6f7)00000000 into 0xbfffee6f
C: copy_buffer: poking (0xbfffe6f8)00000000 into 0xbfffee70
C: copy_buffer: poking (0xbfffe6f9)1D000000 into 0xbfffee71
C: copy_buffer: poking (0xbfffe6fa)0B1D0000 into 0xbfffee72
C: copy_buffer: poking (0xbfffe6fb)000B1D00 into 0xbfffee73
C: copy_buffer: poking (0xbfffe6fc)00000B1D into 0xbfffee74
C: copy_buffer: poking (0xbfffe6fd)0000000B into 0xbfffee75
C: copy_buffer: poking (0xbfffe6fe)00000000 into 0xbfffee76
C: copy_buffer: poking (0xbfffe6ff)00000000 into 0xbfffee77
C: copy_buffer: poking (0xbfffe700)00000000 into 0xbfffee78
C: copy_buffer: poking (0xbfffe701)00000000 into 0xbfffee79
C: copy_buffer: poking (0xbfffe702)10000000 into 0xbfffee7a
C: copy_buffer: poking (0xbfffe703)00100000 into 0xbfffee7b
C: copy_buffer: poking (0xbfffe704)00001000 into 0xbfffee7c
C: copy_buffer: poking (0xbfffe705)08000010 into 0xbfffee7d
C: copy_buffer: poking (0xbfffe706)00080000 into 0xbfffee7e
C: copy_buffer: poking (0xbfffe707)00000800 into 0xbfffee7f
C: copy_buffer: poking (0xbfffe708)00000008 into 0xbfffee80
C: copy_buffer: poking (0xbfffe709)00000000 into 0xbfffee81
C: copy_buffer: poking (0xbfffe70a)00000000 into 0xbfffee82
C: copy_buffer: poking (0xbfffe70b)00000000 into 0xbfffee83
C: copy_buffer: poking (0xbfffe70c)00000000 into 0xbfffee84
C: copy_buffer: poking (0xbfffe70d)66000000 into 0xbfffee85
C: copy_buffer: poking (0xbfffe70e)E4660000 into 0xbfffee86
C: copy_buffer: poking (0xbfffe70f)F2E46600 into 0xbfffee87
C: copy_buffer: poking (0xbfffe710)5BF2E466 into 0xbfffee88
C: copy_buffer: poking (0xbfffe711)005BF2E4 into 0xbfffee89
C: copy_buffer: poking (0xbfffe712)00005BF2 into 0xbfffee8a
C: copy_buffer: poking (0xbfffe713)0000005B into 0xbfffee8b
C: copy_buffer: poking (0xbfffe714)00000000 into 0xbfffee8c
C: copy_buffer: poking (0xbfffe715)66000000 into 0xbfffee8d
C: copy_buffer: poking (0xbfffe716)E4660000 into 0xbfffee8e
C: copy_buffer: poking (0xbfffe717)F2E46600 into 0xbfffee8f
C: copy_buffer: poking (0xbfffe718)5BF2E466 into 0xbfffee90
C: copy_buffer: poking (0xbfffe719)005BF2E4 into 0xbfffee91
C: copy_buffer: poking (0xbfffe71a)00005BF2 into 0xbfffee92
C: copy_buffer: poking (0xbfffe71b)0000005B into 0xbfffee93
C: copy_buffer: poking (0xbfffe71c)00000000 into 0xbfffee94
C: copy_buffer: poking (0xbfffe71d)0D000000 into 0xbfffee95
C: copy_buffer: poking (0xbfffe71e)F00D0000 into 0xbfffee96
C: copy_buffer: poking (0xbfffe71f)E9F00D00 into 0xbfffee97
C: copy_buffer: poking (0xbfffe720)5BE9F00D into 0xbfffee98
C: copy_buffer: poking (0xbfffe721)005BE9F0 into 0xbfffee99
C: copy_buffer: poking (0xbfffe722)00005BE9 into 0xbfffee9a
C: copy_buffer: poking (0xbfffe723)0000005B into 0xbfffee9b
C: copy_buffer: poking (0xbfffe724)00000000 into 0xbfffee9c
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:Entering fstat64 handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:ECX: bfffecdc
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Got successful stat-like call
DEBUG:root:st_dev1: 8
DEBUG:root:st_dev2: 1
DEBUG:root:st_ino: 2230664
DEBUG:root:Cleaning up st_mode
DEBUG:root:Found st_mode parts: ['S_IFREG', '0644']
DEBUG:root:Got part: S_IFREG
DEBUG:root:Interpreting part as S_<CONST>
DEBUG:root:Part value in base 10: 32768
DEBUG:root:Part value in base 8: 0100000
DEBUG:root:New value for tmp: 32768
DEBUG:root:Got part: 0644
DEBUG:root:Interpreting part as base 8 int
DEBUG:root:Part value in base 10: 420
DEBUG:root:Part value in base 8: 0644
DEBUG:root:New value for tmp: 33188
DEBUG:root:Final value for tmp: 33188
DEBUG:root:st_mode: 33188
DEBUG:root:st_nlink: 1
DEBUG:root:st_uid: 0
DEBUG:root:st_gid: 0
DEBUG:root:st_blksize: 4096
DEBUG:root:st_block: 8
DEBUG:root:st_size: 2845
DEBUG:root:st_atime: 1542644838
DEBUG:root:st_mtime: 1542644838
DEBUG:root:st_ctime: 1542057997
DEBUG:root:pid: 7167
DEBUG:root:addr: bfffecdc
C: populate_stat64: child 7167
C: populate_stat64: addr 0xbfffecdc
C: populate_stat64: s 0xbfffe6d0
C: populate_stat64: sizeof(s) 88
C: populate_stat64: st_mode 33188
REG: 1
REG2: 1
sizeof(st.dev): 8
s.st_dev: 2049
sizeof(s.st_rdev): 8
s.st_rdev: 0
sizeof(s.st_ino): 4
s.st_ino: 2230664
sizeof(s.st_mode): 4
s.st_mode: 33188
sizeof(s.st_nlink): 4
s.st_nlink: 1
sizeof(s.st_uid): 4
s.st_uid: 0
sizeof(s.st_gid): 4
s.st_gid: 0
sizeof(s.st_size): 8
s.st_size: 2845
sizeof(s.st_blksize): 4
s.st_blksize: 4096
sizeof(s.st_blocks): 8
s.st_blocks: 8
s.st_ctime: 2018/11/-0800u 13:v
s.st_mtime: 2018/11/-0800u 08:v
s.st_atime: 2018/11/-0800u 08:v
C: copy_buffer: number of writes: 85
C: copy_buffer: buffer data: 
01 08 00 00 00 00 00 00 00 00 00 00 88 09 22 00 A4 81 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1D 0B 00 00 00 00 00 00 00 10 00 00 08 00 00 00 00 00 00 00 66 E4 F2 5B 00 00 00 00 66 E4 F2 5B 00 00 00 00 0D F0 E9 5B 00 00 00 00 C: copy_buffer: buffer data(ASCII): 
           � 	 "  � �                            
 � � [                                                                 f � � [     f � � [     
C: copy_buffer: poking (0xbfffe6d0)00000801 into 0xbfffecdc
C: copy_buffer: poking (0xbfffe6d1)00000008 into 0xbfffecdd
C: copy_buffer: poking (0xbfffe6d2)00000000 into 0xbfffecde
C: copy_buffer: poking (0xbfffe6d3)00000000 into 0xbfffecdf
C: copy_buffer: poking (0xbfffe6d4)00000000 into 0xbfffece0
C: copy_buffer: poking (0xbfffe6d5)00000000 into 0xbfffece1
C: copy_buffer: poking (0xbfffe6d6)00000000 into 0xbfffece2
C: copy_buffer: poking (0xbfffe6d7)00000000 into 0xbfffece3
C: copy_buffer: poking (0xbfffe6d8)00000000 into 0xbfffece4
C: copy_buffer: poking (0xbfffe6d9)88000000 into 0xbfffece5
C: copy_buffer: poking (0xbfffe6da)09880000 into 0xbfffece6
C: copy_buffer: poking (0xbfffe6db)22098800 into 0xbfffece7
C: copy_buffer: poking (0xbfffe6dc)00220988 into 0xbfffece8
C: copy_buffer: poking (0xbfffe6dd)A4002209 into 0xbfffece9
C: copy_buffer: poking (0xbfffe6de)81A40022 into 0xbfffecea
C: copy_buffer: poking (0xbfffe6df)0081A400 into 0xbfffeceb
C: copy_buffer: poking (0xbfffe6e0)000081A4 into 0xbfffecec
C: copy_buffer: poking (0xbfffe6e1)01000081 into 0xbfffeced
C: copy_buffer: poking (0xbfffe6e2)00010000 into 0xbfffecee
C: copy_buffer: poking (0xbfffe6e3)00000100 into 0xbfffecef
C: copy_buffer: poking (0xbfffe6e4)00000001 into 0xbfffecf0
C: copy_buffer: poking (0xbfffe6e5)00000000 into 0xbfffecf1
C: copy_buffer: poking (0xbfffe6e6)00000000 into 0xbfffecf2
C: copy_buffer: poking (0xbfffe6e7)00000000 into 0xbfffecf3
C: copy_buffer: poking (0xbfffe6e8)00000000 into 0xbfffecf4
C: copy_buffer: poking (0xbfffe6e9)00000000 into 0xbfffecf5
C: copy_buffer: poking (0xbfffe6ea)00000000 into 0xbfffecf6
C: copy_buffer: poking (0xbfffe6eb)00000000 into 0xbfffecf7
C: copy_buffer: poking (0xbfffe6ec)00000000 into 0xbfffecf8
C: copy_buffer: poking (0xbfffe6ed)00000000 into 0xbfffecf9
C: copy_buffer: poking (0xbfffe6ee)00000000 into 0xbfffecfa
C: copy_buffer: poking (0xbfffe6ef)00000000 into 0xbfffecfb
C: copy_buffer: poking (0xbfffe6f0)00000000 into 0xbfffecfc
C: copy_buffer: poking (0xbfffe6f1)00000000 into 0xbfffecfd
C: copy_buffer: poking (0xbfffe6f2)00000000 into 0xbfffecfe
C: copy_buffer: poking (0xbfffe6f3)00000000 into 0xbfffecff
C: copy_buffer: poking (0xbfffe6f4)00000000 into 0xbfffed00
C: copy_buffer: poking (0xbfffe6f5)00000000 into 0xbfffed01
C: copy_buffer: poking (0xbfffe6f6)00000000 into 0xbfffed02
C: copy_buffer: poking (0xbfffe6f7)00000000 into 0xbfffed03
C: copy_buffer: poking (0xbfffe6f8)00000000 into 0xbfffed04
C: copy_buffer: poking (0xbfffe6f9)1D000000 into 0xbfffed05
C: copy_buffer: poking (0xbfffe6fa)0B1D0000 into 0xbfffed06
C: copy_buffer: poking (0xbfffe6fb)000B1D00 into 0xbfffed07
C: copy_buffer: poking (0xbfffe6fc)00000B1D into 0xbfffed08
C: copy_buffer: poking (0xbfffe6fd)0000000B into 0xbfffed09
C: copy_buffer: poking (0xbfffe6fe)00000000 into 0xbfffed0a
C: copy_buffer: poking (0xbfffe6ff)00000000 into 0xbfffed0b
C: copy_buffer: poking (0xbfffe700)00000000 into 0xbfffed0c
C: copy_buffer: poking (0xbfffe701)00000000 into 0xbfffed0d
C: copy_buffer: poking (0xbfffe702)10000000 into 0xbfffed0e
C: copy_buffer: poking (0xbfffe703)00100000 into 0xbfffed0f
C: copy_buffer: poking (0xbfffe704)00001000 into 0xbfffed10
C: copy_buffer: poking (0xbfffe705)08000010 into 0xbfffed11
C: copy_buffer: poking (0xbfffe706)00080000 into 0xbfffed12
C: copy_buffer: poking (0xbfffe707)00000800 into 0xbfffed13
C: copy_buffer: poking (0xbfffe708)00000008 into 0xbfffed14
C: copy_buffer: poking (0xbfffe709)00000000 into 0xbfffed15
C: copy_buffer: poking (0xbfffe70a)00000000 into 0xbfffed16
C: copy_buffer: poking (0xbfffe70b)00000000 into 0xbfffed17
C: copy_buffer: poking (0xbfffe70c)00000000 into 0xbfffed18
C: copy_buffer: poking (0xbfffe70d)66000000 into 0xbfffed19
C: copy_buffer: poking (0xbfffe70e)E4660000 into 0xbfffed1a
C: copy_buffer: poking (0xbfffe70f)F2E46600 into 0xbfffed1b
C: copy_buffer: poking (0xbfffe710)5BF2E466 into 0xbfffed1c
C: copy_buffer: poking (0xbfffe711)005BF2E4 into 0xbfffed1d
C: copy_buffer: poking (0xbfffe712)00005BF2 into 0xbfffed1e
C: copy_buffer: poking (0xbfffe713)0000005B into 0xbfffed1f
C: copy_buffer: poking (0xbfffe714)00000000 into 0xbfffed20
C: copy_buffer: poking (0xbfffe715)66000000 into 0xbfffed21
C: copy_buffer: poking (0xbfffe716)E4660000 into 0xbfffed22
C: copy_buffer: poking (0xbfffe717)F2E46600 into 0xbfffed23
C: copy_buffer: poking (0xbfffe718)5BF2E466 into 0xbfffed24
C: copy_buffer: poking (0xbfffe719)005BF2E4 into 0xbfffed25
C: copy_buffer: poking (0xbfffe71a)00005BF2 into 0xbfffed26
C: copy_buffer: poking (0xbfffe71b)0000005B into 0xbfffed27
C: copy_buffer: poking (0xbfffe71c)00000000 into 0xbfffed28
C: copy_buffer: poking (0xbfffe71d)0D000000 into 0xbfffed29
C: copy_buffer: poking (0xbfffe71e)F00D0000 into 0xbfffed2a
C: copy_buffer: poking (0xbfffe71f)E9F00D00 into 0xbfffed2b
C: copy_buffer: poking (0xbfffe720)5BE9F00D into 0xbfffed2c
C: copy_buffer: poking (0xbfffe721)005BE9F0 into 0xbfffed2d
C: copy_buffer: poking (0xbfffe722)00005BE9 into 0xbfffed2e
C: copy_buffer: poking (0xbfffe723)0000005B into 0xbfffed2f
C: copy_buffer: poking (0xbfffe724)00000000 into 0xbfffed30
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:read entry handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 4096
DEBUG:root:Argument from trace: 4096
DEBUG:root:File descriptor from execution: 3
DEBUG:root:File descriptor from trace: 3
DEBUG:root:Cleaned up value 2845
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 4096
DEBUG:root:Argument from trace: 4096
DEBUG:root:Address: 404c80
DEBUG:root:Buffer size from execution: 4096
DEBUG:root:Buffer size from trace: 4096
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 2845
DEBUG:root:Injecting return value 2845
DEBUG:root:Handling syscall
DEBUG:root:Entering llseek entry handler
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:result: 2821
DEBUG:root:result_addr: -1073746736
DEBUG:root:Got successful llseek call
DEBUG:root:Populating result
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:read entry handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 4096
DEBUG:root:Argument from trace: 4096
DEBUG:root:File descriptor from execution: 3
DEBUG:root:File descriptor from trace: 3
DEBUG:root:Cleaned up value 24
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 4096
DEBUG:root:Argument from trace: 4096
DEBUG:root:Address: 404c80
DEBUG:root:Buffer size from execution: 4096
DEBUG:root:Buffer size from trace: 4096
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 24
DEBUG:root:Injecting return value 24
DEBUG:root:Handling syscall
DEBUG:root:Entering close entry handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:Entering openat entry handler
DEBUG:root:Filename from trace: /proc/uptime
DEBUG:root:Filename from execution: /proc/uptime
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 3
DEBUG:root:Injecting return value 3
DEBUG:root:Handling syscall
DEBUG:root:Entering llseek entry handler
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:result: 0
DEBUG:root:result_addr: -1073746176
DEBUG:root:Got successful llseek call
DEBUG:root:Populating result
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 0
DEBUG:root:Injecting return value 0
DEBUG:root:Handling syscall
DEBUG:root:read entry handler
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 8191
DEBUG:root:Argument from trace: 8191
DEBUG:root:File descriptor from execution: 3
DEBUG:root:File descriptor from trace: 3
DEBUG:root:Cleaned up value 18
DEBUG:root:Nooping the current system call in pid: 7167
DEBUG:root:Validating integer argument (trace position: 0 execution position: 0)
DEBUG:root:Argument from execution: 3
DEBUG:root:Argument from trace: 3
DEBUG:root:Validating integer argument (trace position: 2 execution position: 2)
DEBUG:root:Argument from execution: 8191
DEBUG:root:Argument from trace: 8191
DEBUG:root:Address: b7f8f860
DEBUG:root:Buffer size from execution: 8191
DEBUG:root:Buffer size from trace: 8191
DEBUG:root:Applying return conditions
DEBUG:root:Cleaned up value 18
DEBUG:root:Injecting return value 18
DEBUG:root:Handling syscall
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 385, in handle_syscall
    syscall_object.name))
NotImplementedError: Encountered un-ignored syscall entry with no handler: 33(access)
Failed to complete trace
Injector for event:rec_pid 315:7001 failed
```

**Comment by pkmoore** [comment]
Should be implemented if you pull the latest
