### ISSUE TITLE
Exception while testing clang

### ISSUE THREAD

**Issue by liyun-li** [pkmoore/rrapper#59]
## Affected Rapper version

* master
* output_event_number

## Clang Version

```
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: i686-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7.3.0
Candidate multilib: .;@m32
Selected multilib: .;@m32
```

## Reproduction

0. Create a test file called test.c with the following content. (The content probably shouldn't matter)
```
#include <stdio.h>

void main() {
    printf("asdf\n");
}
```
1. Within the same directory, perform the following actions
```
rrtest create -n clang -c 'clang test.c' # change the project name if necessary
rrtest configure -l <ANY_LINE_NUMBER> -n clang
rreplay clang # this is where the error occurs
```
2. See that the following exception occurred
```
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 214, in handle_syscall
    util.validate_syscall(syscall_id, syscall_object)
  File "$HOME/virtualenvs/rrapper/local/lib/python2.7/site-packages/syscallreplay/util.py", line 221, in validate_syscall
    syscall_object.name))
ReplayDeltaError: System call validation failed: from execution: write(4) is not from trace:fstat64
Failed to complete trace
Traceback (most recent call last):
  File "$HOME/virtualenvs/rrapper/bin/rreplay", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'rreplay')()
  File "build/bdist.linux-i686/egg/src/rreplay.py", line 351, in main
  File "build/bdist.linux-i686/egg/src/rreplay.py", line 274, in wait_on_handles
TypeError: list indices must be integers, not str
```

**Comment by pkmoore** [comment]
This looks like an error related to multi-threading/multi-processing.  My working hypothesis is that the trace segment is getting assigned to the wrong process.  I'll need to look at the code that handles this.  I would put this work on hold and try to progress elsewhere until we get this figured out and fixed.

**Comment by liyun-li** [comment]
Picking this up because I was able to reproduce it although I am unsure if it was the same bug. It also appears that this time it's clang's problem not LLVM, unlike last time.

## Environment

![image](https://user-images.githubusercontent.com/6879211/49781746-e84cf980-fce1-11e8-9adb-4d6cc0c07745.png)

## Reproduction

1. `cat /dev/urandom > bigfile.c` until there is little to no space left on device.
2. `strace -f -s 65535 -vvvvv -o clang.strace clang bigfile.c`
3. Optionally ` strace -f -s 65535 -vvvvv -o clang-plus-plus.strace clang++ bigfile.c`

## Question

I understand that this is a threading issue that fails `rrapper` but would you say this belongs to a bug found by crashsim?
