### ISSUE TITLE
implement syscall 202(getegid32)

### ISSUE THREAD

**Issue by akbisw** [pkmoore/rrapper#61]
trace line 189 for sort command 

DEBUG:root:Handling syscall
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 385, in handle_syscall
    syscall_object.name))
NotImplementedError: Encountered un-ignored syscall entry with no handler: 202(getegid32)
Failed to complete trace
Injector for event:rec_pid 221:19809 failed

**Comment by pkmoore** [comment]
Should be supported now.
