### ISSUE TITLE
Syscall entry with no handler: fchmodat

### ISSUE THREAD

**Issue by masofia** [pkmoore/rrapper#68]
Encountered an unhandled system call: `fchmodat`. Checked the latest version of master and I saw this system call is not implemented yet.

The error encountered was:
```
NotImplementedError: Encountered un-ignored syscall entry with no handler: 306(fchmodat)
```

**Comment by pkmoore** [comment]
I've added support here: t https://github.com/pkmoore/rrapper/pull/71

If you get a chance, please pull this and test my changes.  Everything should be fine so I'll merge it in a little bit if I don't hear anything.

**Comment by masofia** [comment]
Tested this branch and it works! Thanks!!

**Comment by aab641** [comment]
Getting this error:

Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 577, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 362, in handle_syscall
    (306, True): file_handlers.fchmodat_entry_handler,
AttributeError: 'module' object has no attribute 'fchmodat_entry_handler'
Failed to complete trace
Injector for event:rec_pid 187:32421 failed

Is it related to this issue?
