### ISSUE TITLE
Socket not implemented

### ISSUE THREAD

**Issue by mnm678** [pkmoore/rrapper#69]
A trace_snip that includes a socket call fails with the following error:
```
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 214, in handle_syscall
    util.validate_syscall(syscall_id, syscall_object)
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/syscallreplay/util.py", line 184, in validate_syscall
    compare_syscall = SYSCALLS[syscall_id][4:]
KeyError: -1
Failed to complete trace
Injector for event:rec_pid 760:18143 failed
```

**Comment by pkmoore** [comment]
Can you provide more information like your strace out file and snip file?

This isn't an unimplemented system call.  The KeyError indicates the application crashed or something yielding an invalid system call number (-1 in this case).

**Comment by pkmoore** [comment]
Can you paste your config as well?  I need to figure out what system call in the snip caused the application to crash.

**Comment by mnm678** [comment]
Sure, here it is:
```
[rr_recording]
rr_dir = /home/alex/.crashsim/whois/

[request_handling_process]
event = 760
pid = 18143
trace_file = /home/alex/.crashsim/whois/trace_snip.strace
trace_start = 0
trace_end = 5
```

**Comment by pkmoore** [comment]
Thanks!  I've replicated your setup and am unable to reproduce the problem.  My replay is successful when it covers the described set of calls.  Would it be possible for you to recreate this test and see if you get the same problem again?

If you do encounter the same problem, could you do a series of tests each replaying ~2 system calls from the problematic area.  The goal is process-of-elimination our way closer to the problematic call.

**Comment by mnm678** [comment]
It seems to be working with the latest version.
