### ISSUE TITLE
Failed to complete trace with cal

### ISSUE THREAD

**Issue by liyun-li** [pkmoore/rrapper#70]
## Issue

When testing the application `cal`, `rrapper` fails to complete its trace with no mutation (meant to do test for reverse time issue).

## Commands used

```
rrtest create -n cal -c 'cal'
rrtest configure -t 175 -n cal
rreplay cal # where it fails
```

## Log
trace_snip.strace:
```
17939 read(3, "\nPST8PDT,M3.2.0,M11.1.0\n", 4096) = 24
17939 close(3)                          = 0
17939 time(NULL)                        = 1543345393 (2018-11-27T11:03:13-0800)
17939 stat64("/etc/localtime", {st_dev=makedev(8, 1), st_ino=2230664, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=2845, st_atime=1543341818 /* 2018-11-27T10:03:38.055919346-0800 */, st_atime_nsec=55919346, st_mtime=1540806663 /* 2018-10-29T02:51:03-0700 */, st_mtime_nsec=0, st_ctime=1541792855 /* 2018-11-09T11:47:35.302949364-0800 */, st_ctime_nsec=302949364}) = 0
17939 ioctl(1, TCGETS, {c_iflags=0x4500, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
```

Exception message:
```
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 574, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 214, in handle_syscall
    util.validate_syscall(syscall_id, syscall_object)
  File "$HOME/virtualenvs/local/lib/python2.7/site-packages/syscallreplay/util.py", line 221, in validate_syscall
    syscall_object.name))
ReplayDeltaError: System call validation failed: from execution: openat(295) is not from trace:ioctl
Failed to complete trace
Injector for event:rec_pid 202:17939 failed
```

**Comment by pkmoore** [comment]
Ok this is a strange one. 

Can you reconfigure your test like this:
```
rrtest configure -t 179 -n cal --sniplen 1
```

This will replay JUST the ioctl() call where the delta occurs.  Let me know what happens here.
