### ISSUE TITLE
Implement dup2

### ISSUE THREAD

**Issue by snahil28** [pkmoore/rrapper#73]
Got below error for split (traceline 173)
```
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 575, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 386, in handle_syscall
    syscall_object.name))
NotImplementedError: Encountered un-ignored syscall entry with no handler: 63(dup2)
Failed to complete trace
Injector for event:rec_pid 203:15101 failed
```

**Comment by snahil28** [comment]
Also an issue for dup3.

**Comment by pkmoore** [comment]
Fixed here. 
https://github.com/pkmoore/rrapper/pull/74

I'll merge this because it's simple.  Re-pull and reinstall and see if that fixes it
