### ISSUE TITLE
AttributeError: 'module' object has no attribute 'fchmodat_entry_handler' Failed to complete trace

### ISSUE THREAD

**Issue by aab641** [pkmoore/rrapper#80]
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 577, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 362, in handle_syscall
    (306, True): file_handlers.fchmodat_entry_handler,
AttributeError: 'module' object has no attribute 'fchmodat_entry_handler'
Failed to complete trace
Injector for event:rec_pid 187:32421 failed

Is it related to this issue?

_Originally posted by @aab641 in https://github.com/pkmoore/rrapper/issues/68#issuecomment-443551021_

**Comment by pkmoore** [comment]
Re-run "pip install --upgrade -r requirements.txt" to make sure you get the latest version of the handlers themselves (syscallreplay module).  I merged this handler a few days ago so it should work.  Let me know what happens!
